opt_out_usage

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Sandbox Release"
  package = load_json(json_path: '../../package.json')
  version = package['version']
  lane :sandbox do
    setup_ci if ENV['CI']
    # ENV['NODE_ENV'] ||= 'production'
    # yarn(
    #   command: 'build',
    #   project_root: '../..'
    # )
    # yarn(
    #   command: 'cap sync',
    #   project_root: '../..'
    # )
    get_certificates
    get_provisioning_profile
    increment_version_number_in_xcodeproj(
      version_number: version,
      xcodeproj: './App.xcodeproj',
      scheme: 'HouseNinja'
    )
    build_app(scheme: "HouseNinja", workspace: "App.xcworkspace")
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_filepath: "./AuthKey.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
