opt_out_usage

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

app_key_id              = ENV["APPSTORE_KEY_ID"]
app_store_issuer_id     = ENV["APPSTORE_ISSUER_ID"]
app_store_key_content   = "#{ENV["APPSTORE_PRIVATE_KEY"]}".gsub('\n', '\\n')
apple_team_id           = ENV["APPLE_TEAM_ID"]
bundle_identifier       = "co.houseninja.application"
gh_user                 = "mileszim"
gh_pat                  = ENV["GHCR_PAT"]
git_basic_authorization = Base64.strict_encode64("#{gh_user}:#{gh_pat}")
provision_profile_name  = "match AppStore co.houseninja.application"
scheme                  = "HouseNinja"
workspace               = "App.xcworkspace"
xcode_project_path      = "./App.xcodeproj"

# get version
package = load_json(json_path: "../../package.json")
version = package["version"]

default_platform(:ios)

platform :ios do
  desc "Sandbox Release"
  lane :sandbox do
    setup_ci if ENV["CI"]
    api_key = app_store_connect_api_key(
      key_id: app_store_key_id,
      issuer_id: app_store_issuer_id,
      key_content: app_store_key_content,
      duration: 1200,  # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
    sync_code_signing(
      api_key: api_key,
      type: "appstore",
      app_identifier: bundle_identifier,
      readonly: false,
      git_basic_authorization: git_basic_authorization,
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: xcode_project_path,
      team_id: apple_team_id,
      bundle_identifier: bundle_identifier,
      profile_name: provision_profile_name,
    )
    increment_version_number_in_xcodeproj(
      version_number: version,
      xcodeproj: xcode_project_path,
      scheme: scheme,
    )
    build_app(
      scheme: scheme,
      workspace: workspace,
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      notify_external_testers: false,
      app_identifier: bundle_identifier,
    )
  end
end
