platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@3.8.0_@capacitor+core@3.8.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@3.8.0_@capacitor+core@3.8.0/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFcm', :path => '../../node_modules/.pnpm/@capacitor-community+fcm@2.0.2/node_modules/@capacitor-community/fcm'
  pod 'CapacitorCommunityHttp', :path => '../../node_modules/.pnpm/@capacitor-community+http@1.4.1/node_modules/@capacitor-community/http'
  pod 'CapacitorCommunityIntercom', :path => '../../node_modules/.pnpm/github.com+houseninjadojo+capacitor-intercom@7c5a337_@capacitor+core@3.8.0/node_modules/@houseninjadojo/capacitor-intercom'
  pod 'CapacitorActionSheet', :path => '../../node_modules/.pnpm/@capacitor+action-sheet@1.0.8_@capacitor+core@3.8.0/node_modules/@capacitor/action-sheet'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@1.1.1_@capacitor+core@3.8.0/node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/.pnpm/@capacitor+browser@1.0.7_@capacitor+core@3.8.0/node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/.pnpm/@capacitor+camera@1.3.1_@capacitor+core@3.8.0/node_modules/@capacitor/camera'
  pod 'CapacitorDevice', :path => '../../node_modules/.pnpm/@capacitor+device@1.1.2_@capacitor+core@3.8.0/node_modules/@capacitor/device'
  pod 'CapacitorDialog', :path => '../../node_modules/.pnpm/@capacitor+dialog@1.0.7_@capacitor+core@3.8.0/node_modules/@capacitor/dialog'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@capacitor+filesystem@1.1.0_@capacitor+core@3.8.0/node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@1.1.4_@capacitor+core@3.8.0/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@1.2.3_@capacitor+core@3.8.0/node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/.pnpm/@capacitor+local-notifications@1.1.0_@capacitor+core@3.8.0/node_modules/@capacitor/local-notifications'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/.pnpm/@capacitor+push-notifications@1.0.9_@capacitor+core@3.8.0/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@1.1.2_@capacitor+core@3.8.0/node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@1.2.2_@capacitor+core@3.8.0/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStorage', :path => '../../node_modules/.pnpm/@capacitor+storage@1.2.5_@capacitor+core@3.8.0/node_modules/@capacitor/storage'
  pod 'HouseninjaCapacitorMixpanel', :path => '../../node_modules/.pnpm/@houseninja+capacitor-mixpanel@0.2.0_@capacitor+core@3.8.0/node_modules/@houseninja/capacitor-mixpanel'
  pod 'RobingenzCapacitorFilePicker', :path => '../../node_modules/.pnpm/@robingenz+capacitor-file-picker@0.3.1_@capacitor+core@3.8.0/node_modules/@robingenz/capacitor-file-picker'
  pod 'CapacitorBranchDeepLinks', :path => '../../node_modules/.pnpm/capacitor-branch-deep-links@4.1.1_@capacitor+core@3.8.0/node_modules/capacitor-branch-deep-links'
  pod 'CapacitorSecureStoragePlugin', :path => '../../node_modules/.pnpm/capacitor-secure-storage-plugin@0.7.1_@capacitor+core@3.8.0/node_modules/capacitor-secure-storage-plugin'
  pod 'SentryCapacitor', :path => '../../node_modules/.pnpm/@sentry+capacitor@0.10.0_@capacitor+core@3.8.0/node_modules/@sentry/capacitor'
end

target 'House Ninja' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging'
end
