name: cd / release

on:
  push:
    branches:
      - sentry-fastlane
  release:
    types:
      - published

env:
  RUBY_VERSION: 3.0.3

jobs:
  testflight:
    runs-on: macos-latest
    env:
      VERSION_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: mathieu-bour/setup-sentry-cli@1.2.0
        with:
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          organization: houseninja
          project: app
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          NODE_ENV: production
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - run: yarn cap sync
        env:
          NODE_ENV: production
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'ios/App'
      - run: bundle exec fastlane ios sandbox
        working-directory: 'ios/App'
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_IDENTIFIER: ${{ secrets.APPLE_APP_IDENTIFIER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: House Ninja.ipa
          path: 'ios/App/House Ninja.ipa'
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: House Ninja.app.dSYM.zip
          path: 'ios/App/House Ninja.app.dSYM.zip'
