on:
  workflow_call:
    secrets:
      DATADOG_API_KEY:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true
      DOTENV_IT_TOKEN:
        required: true

env:
  RUBY_VERSION: 3.0.3
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

jobs:
  ios:
    runs-on: macos-12
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
    steps:
      - name: Datadog
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          logs: |
            - ddsource: "github"
              ddtags: "env:production,service:github-actions,source:github,ci.step:release,ci.service:app,status:info"
              message: "{\"message\":\"[ci/cd] app - starting ios build\", \"level\":\"info\", \"ci.branch\":\"main\", \"ci.service\":\"app\", \"ci.step\":\"release\"}"
              service: "github-actions"
      - uses: mikehardy/buildcache-action@v1
      - uses: mathieu-bour/setup-sentry-cli@v1.3.0
        with:
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          organization: houseninja
          project: app
      - uses: actions/cache/restore@v3
        id: restore-yarn
        with:
          path: |
            package.json
            yarn.lock
            .yarnrc.yml
            .yarn/
            node_modules/
          key: build-yarn-${{ github.run_id }}
          restore-keys: |
            build-yarn-
      - uses: actions/cache/restore@v3
        id: restore-fastlane
        with:
          path: fastlane/
          key: build-fastlane-${{ github.run_id }}
          restore-keys: |
            build-fastlane-
      - uses: actions/cache/restore@v3
        id: restore-ios
        with:
          path: ios/
          key: build-ios-${{ github.run_id }}
          restore-keys: |
            build-ios-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'ios/App'
      - uses: actions/cache/restore@v3
        id: restore-pods
        with:
          path: ios/App/Pods
          key: build-pods-${{ hashFiles('ios/App/Podfile.lock') }}
          restore-keys: |
            build-pods-
      - run: pod install --deployment
        working-directory: 'ios/App'
      - run: npx dotenv-vault pull --yes --dotenvMe=$DOTENV_IT_TOKEN
        working-directory: 'fastlane/'
        env:
          DOTENV_IT_TOKEN: ${{ secrets.DOTENV_IT_TOKEN }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'fastlane/'
      - run: bundle exec fastlane ios sandbox
        working-directory: 'fastlane/'
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: House Ninja.ipa
          path: 'House Ninja.ipa'
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: House Ninja.app.dSYM.zip
          path: 'House Ninja.app.dSYM.zip'
      - uses: actions/cache/save@v3
        id: save-pods
        with:
          path: ios/App/Pods
          key: build-pods-${{ hashFiles('ios/App/Podfile.lock') }}
      - name: Datadog
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          logs: |
            - ddsource: "github"
              ddtags: "env:production,service:github-actions,source:github,ci.step:release,ci.service:app,status:info"
              message: "{\"message\":\"[ci/cd] app - finished ios build\", \"level\":\"info\", \"ci.branch\":\"main\", \"ci.service\":\"app\", \"ci.step\":\"release\"}"
              service: "github-actions"
