name: cd / release

on:
  release:
    types:
      - published
  push:
    branches:
      - split-release

env:
  RUBY_VERSION: 3.0.3

jobs:
  web:
    name: build / web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          NODE_ENV: production
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - run: yarn cap sync
        env:
          NODE_ENV: production
      - run: |
          tar -czvf web.tar.gz dist
          tar -czvf ios.tar.gz ios
          tar -czvf android.tar.gz android
          tar -cf node_modules.tar node_modules
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: package.json
          path: package.json
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: node_modules.tar
          path: node_modules.tar
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: web.tar.gz
          path: web.tar.gz
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: ios.tar.gz
          path: ios.tar.gz
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: android.tar.gz
          path: android.tar.gz
  ios:
    needs: web
    if: success()
    runs-on: macos-latest
    name: build / ios
    steps:
      - uses: mathieu-bour/setup-sentry-cli@1.2.0
        with:
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          organization: houseninja
          project: app
      - uses: actions/download-artifact@v2
        with:
          name: package.json
          path: .
      - uses: actions/download-artifact@v2
        with:
          name: node_modules.tar
          path: .
      - uses: actions/download-artifact@v2
        with:
          name: ios.tar.gz
          path: .
      - run: |
          tar -xzvf ios.tar.gz
          tar -xf node_modules.tar
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'ios/App'
      - uses: actions/cache@v2
        with:
          path: ios/App/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/App/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: pod install
        working-directory: 'ios/App'
      - run: bundle exec fastlane ios sandbox
        working-directory: 'ios/App'
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_IDENTIFIER: ${{ secrets.APPLE_APP_IDENTIFIER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: House Ninja.ipa
          path: 'ios/App/House Ninja.ipa'
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: House Ninja.app.dSYM.zip
          path: 'ios/App/House Ninja.app.dSYM.zip'
  cleanup:
    needs: [ios]
    if: always()
    runs-on: ubuntu-latest
    name: cleanup
    steps:
      - uses: geekyeggo/delete-artifact@v1
        name: clean artifacts
        with:
          name: |
            node_modules.tar
            android.tar.gz
