name: cd / release

concurrency: testflight-release-lock

on:
  release:
    types:
      - published

env:
  RUBY_VERSION: 3.0.3
  BUILD_ENV: production

jobs:
  build:
    uses: ./.github/workflows/build.capacitor.yml
    with:
      environment: ${{ env.BUILD_ENV }}
  release-web:
    needs: build
    if: success()
    uses: ./.github/workflows/release.web.yml
    with:
      environment: ${{ env.BUILD_ENV }}
  build-ios:
    needs: build
    if: success()
    uses: ./.github/workflows/build.ios.yml
    with:
      environment: ${{ env.BUILD_ENV }}
  release-ios:
    needs: build-ios
    if: success()
    uses: ./.github/workflows/release.ios.yml
    with:
      environment: ${{ env.BUILD_ENV }}
  cleanup:
    needs: [release-web, release-ios]
    if: always()
    runs-on: ubuntu-latest
    name: cleanup
    steps:
      - uses: geekyeggo/delete-artifact@v1
        name: clean artifacts
        with:
          name: |
            node_modules.tar.gz
            android.tar.gz
            App.tar.gz
            ios.tar.gz
