name: cd / release

concurrency: testflight-release-lock

on:
  push:
    branches:
      - improved-builds
  # release:
  #   types:
  #     - published

env:
  BUILD_ENV: production

jobs:
  build:
    uses: ./.github/workflows/build.capacitor.yml
    secrets: inherit
    with:
      environment: production
  release-web:
    needs: build
    if: success()
    uses: ./.github/workflows/release.web.yml
    secrets: inherit
    with:
      environment: production
  build-ios:
    needs: build
    if: success()
    uses: ./.github/workflows/build.ios.yml
    secrets: inherit
    with:
      environment: production
  release-ios:
    needs: build-ios
    if: success()
    uses: ./.github/workflows/release.ios.yml
    secrets: inherit
    with:
      environment: production
  cleanup:
    needs: [release-web, release-ios]
    if: always()
    runs-on: ubuntu-latest
    name: cleanup
    steps:
      - uses: geekyeggo/delete-artifact@v1
        name: clean artifacts
        with:
          name: |
            node_modules.tar.gz
            android.tar.gz
            App.tar.gz
            ios.tar.gz
