name: cd / release

on:
  push:
    branches:
      - fastlane
  # release:
  #   types:
  #     - published

env:
  RUBY_VERSION: 3.0.3
  NODE_ENV: production

jobs:
  testflight:
    runs-on: macos-latest
    env:
      VERSION_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
        shell: bash
      - run: yarn build:env
        shell: bash
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - run: yarn cap sync
        shell: bash
      - run: echo $APPSTORE_PRIVATE_KEY > ./AuthKey.p8
        working-directory: 'ios/App'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'ios/App'
      - run: bundle exec fastlane ios sandbox
        working-directory: 'ios/App'
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
