name: ci / bundlewatch

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  API_ACTIVE_STORAGE_HOST: ${{ secrets.API_ACTIVE_STORAGE_HOST }}
  API_HOST: ${{ secrets.API_HOST }}
  APP_HOST: ${{ secrets.APP_HOST }}
  APP_SCHEME: ${{ secrets.APP_SCHEME }}
  AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
  AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
  AUTH_CONNECTION: ${{ secrets.AUTH_CONNECTION }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  BRANCH_KEY: ${{ secrets.BRANCH_KEY }}
  INTERCOM_APP_ID: ${{ secrets.INTERCOM_APP_ID }}
  INTERCOM_IDENTITY_VERIFICATION_SECRET_WEB: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_WEB }}
  INTERCOM_IDENTITY_VERIFICATION_SECRET_IOS: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_IOS }}
  INTERCOM_IDENTITY_VERIFICATION_SECRET_ANDROID: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_ANDROID }}
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
