name: ci / deps / auto-merge

on:
  pull_request:
    branches:
      - 'dependabot/**'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          config: .github/auto-merge.yml
          github-token: ${{ secrets.DP_AUTOMERGE_GH_TOKEN }}
