name: ci / lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

# env:
#   API_ACTIVE_STORAGE_HOST: ${{ secrets.API_ACTIVE_STORAGE_HOST }}
#   API_HOST: ${{ secrets.API_HOST }}
#   APP_HOST: ${{ secrets.APP_HOST }}
#   APP_SCHEME: ${{ secrets.APP_SCHEME }}
#   AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
#   AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
#   AUTH_CONNECTION: ${{ secrets.AUTH_CONNECTION }}
#   AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
#   BRANCH_KEY: ${{ secrets.BRANCH_KEY }}
#   INTERCOM_APP_ID: ${{ secrets.INTERCOM_APP_ID }}
#   INTERCOM_IDENTITY_VERIFICATION_SECRET_WEB: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_WEB }}
#   INTERCOM_IDENTITY_VERIFICATION_SECRET_IOS: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_IOS }}
#   INTERCOM_IDENTITY_VERIFICATION_SECRET_ANDROID: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_ANDROID }}
#   MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
#   SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  hbs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint:hbs
  js:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint:js
  css:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint:css
