name: ci / lint

on:
  pull_request:
  push:
    branches:
      - main

env:
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  templates:
    name: lint hbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint:hbs
  js:
    name: lint js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: |
          export $(echo $ENV_FILE | xargs)
          yarn lint:js
  css:
    name: lint css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: |
          export $(echo $ENV_FILE | xargs)
          yarn lint:css
