name: ci / lint / commits

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  commits:
    name: pull request title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # if: |
    #   github.event.action == 'opened' ||
    #   github.event.action == 'reopened' ||
    #   (github.event.action == 'edited' && github.event.changes.title != null)
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
