name: ci / release / generate

concurrency: release-lock

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "ci / tests"
    branches:
      - main
    types:
      - completed

jobs:
  semantic-release:
    name: generate github release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
  reporter:
    needs: semantic-release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Datadog
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          logs: |
            - ddsource: "github"
              ddtags: "env:production,service:github-actions,source:github,ci.step:version-increment,ci.service:app,status:info"
              message: "{\"message\":\"[ci/cd] app - trying to increment version\", \"level\":\"info\", \"ci.branch\":\"${{ github.ref_name }}\", \"ci.service\":\"app\", \"ci.step\":\"version-bump\"}"
              service: "github-actions"
