name: ci / tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  test:
    name: ember test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: mkdir -p tmp
      - run: |
          export $(echo $ENV_FILE | xargs)
          yarn test:ember -o tmp/app
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: tmp/app/
