name: ci / tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

env:
  API_ACTIVE_STORAGE_HOST: ${{ secrets.API_ACTIVE_STORAGE_HOST }}
  API_HOST: ${{ secrets.API_HOST }}
  APP_HOST: ${{ secrets.APP_HOST }}
  APP_SCHEME: ${{ secrets.APP_SCHEME }}
  AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
  AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
  AUTH_CONNECTION: ${{ secrets.AUTH_CONNECTION }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  BRANCH_KEY: ${{ secrets.BRANCH_KEY }}
  INTERCOM_APP_ID: ${{ secrets.INTERCOM_APP_ID }}
  INTERCOM_IDENTITY_VERIFICATION_SECRET_WEB: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_WEB }}
  INTERCOM_IDENTITY_VERIFICATION_SECRET_IOS: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_IOS }}
  INTERCOM_IDENTITY_VERIFICATION_SECRET_ANDROID: ${{ secrets.INTERCOM_IDENTITY_VERIFICATION_SECRET_ANDROID }}
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.changed-files.outputs.only_changed == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            android/**
            ios/**
            docs/**
            .github/**
            .vscode/**
            bin/build.sh
            vendor/ssl/**
            README.md
            CHANGELOG.md

  test:
    if: needs.skip-check.outputs.should-skip
    name: ember test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Datadog
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          logs: |
            - ddsource: "github"
              ddtags: "env:test,service:github-actions,source:github,ci.step:version-increment,ci.service:app,ci.branch:${{ github.ref_name }},status:info"
              message: "{\"message\":\"[ci/cd] app - tests starting for ${{ github.ref_name }}\", \"level\":\"info\", \"ci.branch\":\"${{ github.ref_name }}\", \"ci.service\":\"app\", \"ci.step\":\"tests\"}"
              service: "github-actions"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: mkdir -p tmp
      - run: yarn test:ci -o tmp/app
        env:
          COVERAGE: true
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          DOTENV_ENABLED: false
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: tmp/app/
      - uses: slavcodev/coverage-monitor-action@v1
        if: contains(github.event.pull_request.user.login, 'dependabot[bot]') == false
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "coverage/coverage-summary.json"
          status_context: ci / tests / coverage
          check: true
          threshold_alert: 10
          threshold_warning: 10
          threshold_metric: lines
      # - uses: romeovs/lcov-reporter-action@v0.3.1
      #   with:
      #     lcov-file: ./coverage/lcov.info
      #     github-token: ${{ github.token }}
      #     filter-changed-files: true
      #     delete-old-comments: true
      - name: Datadog
        uses: masci/datadog@v1
        if: always()
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          logs: |
            - ddsource: "github"
              ddtags: "env:test,service:github-actions,source:github,ci.step:tests,ci.service:app,ci.branch:${{ github.ref_name }},status:${{ job.status }}"
              message: "{\"message\":\"[ci/cd] app - tests finished for ${{ github.ref_name }} - ${{ job.status }}\", \"level\":\"${{ job.status }}\", \"ci.branch\":\"${{ github.ref_name }}\", \"ci.service\":\"app\", \"ci.step\":\"tests\"}"
              service: "github-actions"

