name: ci / tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: ember test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: mkdir -p tmp
      - run: yarn test:ci -o tmp/app
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: tmp/app/
